[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

[lib]
name = "aoc2024lib"
path = "src/lib.rs"

[[bin]]
name = "aoc2024"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
criterion = "0.5.1"

[[bench]]
name = "aoc2024bench"
harness = false
