name: Rust

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: wget https://github.com/sharkdp/hyperfine/releases/download/v1.19.0/hyperfine_1.19.0_amd64.deb; sudo dpkg -i hyperfine_1.19.0_amd64.deb
      - name: Build
        run: cargo build --release
      - name: Run tests
        run: ./test.sh > benchmark_report.md
      - name: Summary
        run:  cat benchmark_report.md >> $GITHUB_STEP_SUMMARY